### ISSUE TITLE
Index out of bounds in stream.zig

### ISSUE THREAD

**Issue by jdgriffith** [ianic/websocket.zig#1]
I'm experiencing an index out of bounds error and I'm not sure there is something I can do to correct this in my code since it merely listens for the next message. 

https://github.com/ianic/websocket.zig/blob/main/src/stream.zig#L238

![Screenshot 2023-11-20 at 9 30 51 AM](https://github.com/ianic/websocket.zig/assets/872496/d229477f-03ae-4afc-88a1-cb1502767794)

Let me know if there is more info I can give to help diagnose this.

**Comment by ianic** [comment]
Seams that Zig's tls implementation still has some open [issues](https://github.com/ziglang/zig/issues?q=is%3Aissue+is%3Aopen+tls+). I didn't connect any of them with this particular error but let's try to remove it as dependency. 

We can use some sidecar tcp->tls proxy. I tried with [envoy](https://github.com/envoyproxy/envoy/releases). Downloaded bin for my platform, make config and start it.

config.yml:
```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          cluster: service-https
          stat_prefix: wss_passthrough
  clusters:
  - name: service-https
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service-https
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: socket.polygon.io
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```


```sh
 ./envoy-1.28.0-linux-aarch_64 --config-path ./config.yaml
```

This example connect to the remote wss endpoint through local proxy which handles tls.
```Zig
const std = @import("std");
const ws = @import("ws");
const assert = std.debug.assert;
const Allocator = std.mem.Allocator;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const uri = "wss://socket.polygon.io/stocks";
    const proxy_host = "127.0.0.1";
    const proxy_port = 10000;

    var tcp = try std.net.tcpConnectToHost(allocator, proxy_host, proxy_port);
    defer tcp.close();
    var cli = try ws.client(allocator, tcp.reader(), tcp.writer(), uri);
    defer cli.deinit();

    while (cli.nextMessage()) |msg| {
        defer msg.deinit();
        std.debug.print("{s}\n", .{msg.payload});
    }
}
```

Getting result:
```
[{"ev":"status","status":"connected","message":"Connected Successfully"}]
[{"ev":"status","status":"auth_timeout","message":"No authentication request received."}]
```
